//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Fornecedores = new HashSet<Fornecedor>();
            this.Produtos = new HashSet<Produto>();
        }
    
        public int categoriaId { get; set; }
        public string categoriaNome { get; set; }
        public string categoriaDescricao { get; set; }
    
        public virtual ICollection<Fornecedor> Fornecedores { get; set; }
        public virtual ICollection<Produto> Produtos { get; set; }
    }
}
