//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pedidos = new HashSet<Pedido>();
        }
    
        public int clienteId { get; set; }
        public string clienteNome { get; set; }
        public string clienteEndereco { get; set; }
        public string clienteTelefone { get; set; }
        public string clienteEmail { get; set; }
    
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
