//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public int fornecedorId { get; set; }
        public string fornecedorNome { get; set; }
        public string fornecedorEndereco { get; set; }
        public string fornecedorTelefone { get; set; }
        public string fornecedorEmail { get; set; }
        public string fornecedorHome { get; set; }
        public Nullable<int> categoriaId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
