//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Itens = new HashSet<Item>();
        }
    
        public int pedidoId { get; set; }
        public int clienteId { get; set; }
        public System.DateTime pedidoData { get; set; }
        public Nullable<System.DateTime> pedidoEntrega { get; set; }
        public Nullable<decimal> pedidoValor { get; set; }
        public string pedidoStatus { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Item> Itens { get; set; }

        public static object Take(int qtdVendas)
        {
            throw new NotImplementedException();
        }
    }
}
