//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Itens = new HashSet<Item>();
        }
    
        public int produtoId { get; set; }
        public string produtoNome { get; set; }
        public decimal produtoPreco { get; set; }
        public decimal produtoDesconto { get; set; }
        public byte[] produtoImagem { get; set; }
        public Nullable<int> produtoCategoriaId { get; set; }
    
        public virtual ICollection<Item> Itens { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
