//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int usuarioId { get; set; }
        public string usuarioNome { get; set; }
        public string usuarioSenha { get; set; }
        public string usuarioPerfil { get; set; }
    }
}
